### ISSUE TITLE
Data to work with folder

### ISSUE THREAD

**Issue by prasannabiswas-iitb** [jsubram/Sarcasm-Detection-Using-Emoji#1]
The folder is not available. Please upload the datasets.

**Comment by vsridh** [comment]
The datasets have been added to /Data. Apologies for the inconvenience.

**Comment by prasannabiswas-iitb** [comment]
Thankyou.

**Comment by prasannabiswas-iitb** [comment]
Where I can find the labels for the dataset added i.e for "final facebook dataset and final twitter dataset"?

**Comment by vsridh** [comment]
The labels have been uploaded. Sorry about that.

**Comment by prasannabiswas-iitb** [comment]
Thankyou Sir.
